namespace.prefix = "mozilla::dom::"

[class."BrowsingContext"]
semType = "browsingContext"
lifecycle = true
# We sample at constructor time from arguments
identityMethod = "constructor"
[class."BrowsingContext".identity]
# We can just pull this out of the arguments at construction time, but
# alternately could have done:
#   browsingContext.eval = "mParentWindow.mRawPtr"
# but that won't be valid at the start of the constructor and so we need to pick
# some time to sample it.
windowContext.arg = "aParentWindow"

[class."WindowContext"]
semType = "windowContext"
lifecycle = true
# We sample at constructor time from arguments
identityMethod = "constructor"
[class."WindowContext".identity]
browsingContext.arg = "aBrowsingContext"

