namespace.prefix = "mozilla::net::"

[class."ParentChannelListener"]

[class."DocumentLoadListener"]
semType = "loadListener"
lifecycle = true
[class."DocumentLoadListener".identity]
uri.eval = "mChannelCreationURI.mRawPtr->mSpec"

[trace."DocumentLoadListener::TriggerRedirectToRealChannel"]
[trace."DocumentLoadListener::RedirectToRealChannelFinished"]
[trace."DocumentLoadListener::FinishReplacementChannelSetup"]

[class."DocumentChannelParent"]
semType = "docChannelParent"
lifecycle = true
identityMethod = "DocumentChannelParent::Init"
[class."DocumentChannelParent".identity]
# this needs to be sampled at the end of DocumentChannelParent::Init.
loadListener.eval = "mDocumentLoadListener.mRawPtr"

#[trace."DocumentChannelParent::Init"]

[class."DocumentChannelChild"]

[class."HttpChannelParent"]
[class."HttpChannelParent".identity]
# For now just pierce the channel to get the URI
uri.eval = "mChannel.mRawPtr->mURI.mRawPtr->mSpec"

[trace."HttpChannelParent::RecvRedirect2Verify"]
