[trace."mozilla::dom::ServiceWorkerRegistrationInfo::FinishActivate"]

[trace."mozilla::dom::ServiceWorkerUpdateJob::ComparisonResult"]
capture=[
  "Status",
  "aInCacheAndEqual",
]

[trace."mozilla::dom::serviceWorkerScriptCache::PurgeCache"]
capture=[
  "aPrincipal->mURI.mRawPtr->mSpec"
]

[trace."mozilla::dom::ServiceWorkerRegistrar::RegisterServiceWorker"]

[trace."mozilla::dom::RemoteWorkerController::ExecServiceWorkerOp"]
capture=[
  "aArgs->mType"
]

[disabled."mozilla::net::InterceptedHttpChannel::AsyncOpen"]

[trace."mozilla::net::InterceptedHttpChannel::ResetInterception"]

[class."mozilla::net::InterceptedHttpChannel"]
state=[
  "mURI.mRawPtr->mSpec"
]

[trace."mozilla::dom::workerinternals::LoadMainScript"]
capture=[
  "aScriptURL"
]

[trace."mozilla::dom::FetchEventOp::Exec"]
